export const STATES = [
    {"id" : "AN", "value" : "Andaman and Nicobar Islands"},
    {"id" : "AP", "value" : "Andhra Pradesh"},
    {"id" : "AR", "value" : "Arunachal Pradesh"},
    {"id" : "AS", "value" : "Assam"},
    {"id" : "BH", "value" : "Bihar"},
    {"id" : "CG", "value" : "Chhattisgarh"},
    {"id" : "DD", "value" : "Daman and Diu"},
    {"id" : "DL", "value" : "Delhi"},
    {"id" : "DN", "value" : "Dadra and Nagar Haveli"},
    {"id" : "GA", "value" : "Goa"},
    {"id" : "GJ", "value" : "Gujarat"},
    {"id" : "HR", "value" : "Haryana"},
    {"id" : "HP", "value" : "Himachal Pradesh"},
    {"id" : "JK", "value" : "Jammu & Kashmir"},
    {"id" : "JH", "value" : "Jharkhand"},
    {"id" : "KA", "value" : "Karnataka"},
    {"id" : "KL", "value" : "Kerala"},
    {"id" : "LD", "value" : "Lakshadweep"},
    {"id" : "MP", "value" : "Madhya Pradesh"},
    {"id" : "MH", "value" : "Maharashtra"},
    {"id" : "MN", "value" : "Manipur"},
    {"id" : "ML", "value" : "Meghalaya"},
    {"id" : "MZ", "value" : "Mizoram"},
    {"id" : "NL", "value" : "Nagaland"},
    {"id" : "OR", "value" : "Orissa"},
    {"id" : "PB", "value" : "Punjab"},
    {"id" : "PY", "value" : "Puducherry"},
    {"id" : "RJ", "value" : "Rajasthan"},
    {"id" : "SK", "value" : "Sikkim"},
    {"id" : "TN", "value" : "Tamil Nadu"},
    {"id" : "TS", "value" : "Telangana"},
    {"id" : "TR", "value" : "Tripura"},
    {"id" : "UP", "value" : "Uttar Pradesh"},
    {"id" : "UK", "value" : "Uttarakhand"},
    {"id" : "WB", "value" : "West Bengal"}
]